# Configuration file for the application
# IMPORTANT: This file contains sensitive information and should not be committed to version control

# Database Configuration
# Replace with your MongoDB connection string (e.g., from MongoDB Atlas)
database:
  mongodb_uri: "mongodb+srv://svwpzi:2nwygk@cluster0.tidunfj.mongodb.net/?retryWrites=true&w=majority"
  db_name: "ticketsystem"

# Server Configuration
server:
  port: 5000
  session_secret: "CHANGE-THIS-TO-A-SECURE-RANDOM-STRING-IN-PRODUCTION"

# Email Configuration (Supabase + Resend)
# Get these from your Supabase project and Resend account
email:
  supabase_url: "https://bmdjczrzluawslbjlazm.supabase.co"
  supabase_anon_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZGpjenJ6bHVhd3NsYmpsYXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MDk1NTIsImV4cCI6MjA3NDk4NTU1Mn0.7BMkMJNelKUOc_cFvN8xXmHDEM--JIBBzE9CZQF9EZA"
  resend_api_key: "re_egLsdFfp_3BdpuodTx2kuTkQdr4HJBmYo"
  base_url: "https://support.encorebot.me"  # Change to your production URL when deploying

# Admin Configuration
admin:
  default_email: "aliveisalive8354@gmail.com"
